<a href="https://colab.research.google.com/github/domitru/GB_HomeWork_Python/blob/main/GB_Python_HomeWork_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашняя работа.
## Задача 44:
- В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?
<hr>
<p> import random </p>
<p> lst = ['robot'] * 10 </p>
<p> lst += ['human'] * 10 </p>
<p> random.shuffle(lst) </p>
<p> data = pd.DataFrame({'whoAmI':lst}) </p>
<p> data.head() </p>
<hr>
- Статья про one hot вид: 
-  ->> https://colab.research.google.com/drive/1qKamnDiRmpRZkpiqWPkunBdAhmzhMcGz?usp=sharing
<hr>
<br>

<p> import numpy as np </p>
<p> import matplotlib.pyplot as plt </p>
<p> corrs = penguins.corr() </p>
<p>  mask = np.triu(np.ones_like(corrs, dtype=bool)) </p>
<p> f, ax = plt.subplots(figsize=(11, 9)) </p>
<p> cmap = sns.diverging_palette(230, 20, as_cmap=True) </p>
<p> sns.heatmap(corrs, mask=mask, cmap=cmap, vmax=.3, center=0, <wbr> 
              square=True, linewidths=.5, cbar_kws={"shrink": .5}) </p>

In [1]:
import pandas as pd
import random

lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  human
2  robot
3  human
4  human

In [2]:
# 0 - robot, 1 - human

data=pd.DataFrame(random.sample(['0', '1']*10, 20), columns={'whoAmI'})
data.head(20)

   whoAmI
0       1
1       0
2       1
3       0
4       0
5       1
6       1
7       0
8       1
9       1
10      1
11      1
12      1
13      1
14      0
15      0
16      0
17      0
18      0
19      0